version: '3'
services:
  web:
#    image: ${ECR_REPOSITORY}:web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - php
  php:
#    image: ${ECR_REPOSITORY}:php
    build:
      context: .
      dockerfile: ./php/Dockerfile
  mysql:
#    image: ${ECR_REPOSITORY}:mysql
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - ${MYSQL_PORT}:3306
  smtp:
    image: namshi/smtp
    restart: always
    env_file: ./.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ./.data/phpmyadmin/sessions:/sessions
